Updated README.md, DEV_DOC.md wip

diff --git a/Inception/Makefile b/Inception/Makefile
--- a/Inception/Makefile
+++ b/Inception/Makefile
@@ -1,11 +1,26 @@
 composeFile := srcs/docker-compose.yml
 bonusFile := srcs/docker-compose.bonus.yml
 dataDir := /home/nraatika/data
+secretDir := ./secrets
+requiredFiles := ftp_user_pw.txt mariadb_root_pw.txt  mariadb_user_pw.txt  wp_bestuser_pass.txt  wp_user_pass.txt
 s ?=
 
 all: up
 
-up:
+check_secrets:
+	@echo "Checking for required secrets in $(secretDir)..."
+	@for file in $(requiredFiles); do \
+		if [ ! -s $(secretDir)/$$file ]; then \
+		echo "Error: Missing secret file: $(secretDir)/$$file"; \
+			echo "Please ensure all passwords exist in the secrets folder."; \
+			exit 1; \
+		fi; \
+	done
+	@echo "All secrets found. Proceeding..."
+	if [ ! -f srcs/.env ]; then \
+	@echo "Warning: no .env file found in srcs/, using default values";
+
+up: check_secrets
 	@mkdir -p $(dataDir)/mariadb $(dataDir)/wordpress
 	docker compose -f $(composeFile) up -d --build
 
@@ -19,11 +34,11 @@ status:
 	docker compose -f $(composeFile) -f $(bonusFile) ps
 	@echo ""
 
-status-network:
+network:
 	docker network ls
 	@echo ""
 
-status-volumes:
+volume:
 	docker volume ls
 	@echo "---"
 	docker volume inspect mariadb_data
@@ -44,9 +59,6 @@ else
 	docker compose -f $(composeFile) -f $(bonusFile) logs $s -f;
 endif
 
-tls-check:
-
-
 fclean: down
 	-docker stop $$(docker ps -qa) 2>/dev/null || true
 	-docker rm $$(docker ps -qa) 2>/dev/null || true
@@ -59,4 +71,4 @@ fclean: down
 
 re: fclean all
 
-.PHONY: all up down status status-network status-volumes logs tls-check fclean re
+.PHONY: all check_secrets up down status network volume logs fclean re
